"""Safe declarative contracts for evidence-grounded generative interfaces."""

from scitaste.generative_ui.fixtures import (
    build_blocked_run_fixture,
    build_fixture_surfaces,
    build_next_step_fixture,
    build_paper_status_fixture,
    build_project_overview_fixture,
    build_run_comparison_fixture,
    fixture_snapshot_binding,
)
from scitaste.generative_ui.interaction import (
    DuplicateEventError,
    ProposalReceipt,
    RevisionConflictError,
    StaleSurfaceError,
    SurfaceEvent,
    SurfaceInteractionError,
    SurfaceSession,
    UnknownActionError,
    make_surface_event,
)
from scitaste.generative_ui.models import (
    ActionBinding,
    ActionProposal,
    CompareRunsPayload,
    ComponentSpec,
    EvidenceRef,
    InspectArtifactPayload,
    ProposeTransitionPayload,
    RequestApprovalPayload,
    SnapshotBinding,
    SurfaceRevision,
    SurfaceSpec,
)
from scitaste.generative_ui.projection import (
    FixedApplicationShell,
    RendererAction,
    RendererComponent,
    RendererDocument,
    project_surface,
)
from scitaste.generative_ui.registry import (
    COMPONENT_REGISTRY,
    ApprovalSubject,
    EvidenceKind,
    ProposalKind,
    SurfacePurpose,
    TrustedComponent,
)

__all__ = [
    "COMPONENT_REGISTRY",
    "ActionBinding",
    "ActionProposal",
    "ApprovalSubject",
    "CompareRunsPayload",
    "ComponentSpec",
    "DuplicateEventError",
    "EvidenceKind",
    "EvidenceRef",
    "FixedApplicationShell",
    "InspectArtifactPayload",
    "ProposalKind",
    "ProposalReceipt",
    "ProposeTransitionPayload",
    "RendererAction",
    "RendererComponent",
    "RendererDocument",
    "RequestApprovalPayload",
    "RevisionConflictError",
    "SnapshotBinding",
    "StaleSurfaceError",
    "SurfaceEvent",
    "SurfaceInteractionError",
    "SurfacePurpose",
    "SurfaceRevision",
    "SurfaceSession",
    "SurfaceSpec",
    "TrustedComponent",
    "UnknownActionError",
    "build_blocked_run_fixture",
    "build_fixture_surfaces",
    "build_next_step_fixture",
    "build_paper_status_fixture",
    "build_project_overview_fixture",
    "build_run_comparison_fixture",
    "fixture_snapshot_binding",
    "make_surface_event",
    "project_surface",
]
