"""Evidence-grounded narrative, writing contracts, drafting, and critics."""

from scitaste.writing.argument import (
    ClaimPresentationContract,
    EvidenceCarrierContract,
    MaterialLimitationContract,
    PaperArgumentAssessment,
    PaperArgumentContract,
    PaperArgumentGap,
    PaperEntryPointContract,
    SectionDeliveryContract,
    assess_paper_argument,
)
from scitaste.writing.critics import WritingCriticSuite
from scitaste.writing.drafter import ContractDrafter
from scitaste.writing.narrative import NarrativeTasteReview, review_narrative
from scitaste.writing.semantic import (
    EvidencePaperDraftNode,
    WritingTasteNode,
    render_evidence_paper_markdown,
    writing_node_types,
)
from scitaste.writing.semantic_models import (
    EVIDENCE_PAPER_DRAFT_NODE,
    EvidencePaperCitationInput,
    EvidencePaperClaimInput,
    EvidencePaperDraftInput,
    EvidencePaperDraftProposal,
    EvidencePaperDraftSection,
    EvidencePaperEvidenceInput,
    EvidencePaperParagraph,
    EvidencePaperParagraphRole,
    MaterialWritingLimitation,
    PaperClaimSupport,
    SemanticWritingTasteFinding,
    WritingRevisionAction,
    WritingTasteReviewProposal,
    WritingTasteSectionInput,
    WritingTasteSemanticInput,
)
from scitaste.writing.taste import (
    WritingTasteAssessment,
    WritingTasteDimension,
    WritingTasteFinding,
    assess_writing_taste,
)
from scitaste.writing.venue_taste import (
    PaperArchetype,
    VenueWritingTasteContext,
    VenueWritingTasteInspection,
    VenueWritingTasteProfile,
    build_venue_writing_taste_context,
    inspect_venue_writing_taste,
)

__all__ = [
    "EVIDENCE_PAPER_DRAFT_NODE",
    "ClaimPresentationContract",
    "ContractDrafter",
    "EvidenceCarrierContract",
    "EvidencePaperCitationInput",
    "EvidencePaperClaimInput",
    "EvidencePaperDraftInput",
    "EvidencePaperDraftNode",
    "EvidencePaperDraftProposal",
    "EvidencePaperDraftSection",
    "EvidencePaperEvidenceInput",
    "EvidencePaperParagraph",
    "EvidencePaperParagraphRole",
    "MaterialLimitationContract",
    "MaterialWritingLimitation",
    "NarrativeTasteReview",
    "PaperArchetype",
    "PaperArgumentAssessment",
    "PaperArgumentContract",
    "PaperArgumentGap",
    "PaperClaimSupport",
    "PaperEntryPointContract",
    "SectionDeliveryContract",
    "SemanticWritingTasteFinding",
    "VenueWritingTasteContext",
    "VenueWritingTasteInspection",
    "VenueWritingTasteProfile",
    "WritingCriticSuite",
    "WritingRevisionAction",
    "WritingTasteAssessment",
    "WritingTasteDimension",
    "WritingTasteFinding",
    "WritingTasteNode",
    "WritingTasteReviewProposal",
    "WritingTasteSectionInput",
    "WritingTasteSemanticInput",
    "assess_paper_argument",
    "assess_writing_taste",
    "build_venue_writing_taste_context",
    "inspect_venue_writing_taste",
    "render_evidence_paper_markdown",
    "review_narrative",
    "writing_node_types",
]
