"""Project-superordinate compute resource registry."""

from scitaste.resources.registry import (
    ApiModelDefinition,
    ComputeResourceCatalog,
    ComputeResourceRuntime,
    CredentialBindingSource,
    GpuHostDefinition,
    LoadedComputeResourceCatalog,
    ModelCheckpointDefinition,
    ObservationMethod,
    ObservationStatus,
    ProjectResourceBinding,
    ProjectResourceBindingInspection,
    ResourceAccessBindingItem,
    ResourceAccessStatus,
    ResourceKind,
    ResourceObservation,
    ResourceRegistryStatus,
    SshRemoteForward,
    inspect_compute_resource_catalog,
    inspect_project_resource_binding,
    inspect_resource_access,
    load_compute_resource_catalog,
    load_project_resource_binding,
    load_resource_observation,
)

__all__ = [
    "ApiModelDefinition",
    "ComputeResourceCatalog",
    "ComputeResourceRuntime",
    "CredentialBindingSource",
    "GpuHostDefinition",
    "LoadedComputeResourceCatalog",
    "ModelCheckpointDefinition",
    "ObservationMethod",
    "ObservationStatus",
    "ProjectResourceBinding",
    "ProjectResourceBindingInspection",
    "ResourceAccessBindingItem",
    "ResourceAccessStatus",
    "ResourceKind",
    "ResourceObservation",
    "ResourceRegistryStatus",
    "SshRemoteForward",
    "inspect_compute_resource_catalog",
    "inspect_project_resource_binding",
    "inspect_resource_access",
    "load_compute_resource_catalog",
    "load_project_resource_binding",
    "load_resource_observation",
]
